org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx8G

essential.defaults.loom.yarn=false
essential.defaults.loom.fabric-api=true
essential.defaults.loom.fabric-kotlin=true
loom.ignoreDependencyLoomVersionValidation=true

mod_version=0.1.0
mod_group=org.zephy.kotlinhotreload
mod_name=KotlinHotReload
